### ISSUE TITLE
subfields

### ISSUE THREAD

**Issue by teto** [luismartingarcia/protocol#2]
Thanks for the program, it's very simple yet very useful.

In case you are bored,  you would be interested in showing some kind of subfields, so that   
```
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|     PREAMBLE                                 |        2nd field           |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
becomes
```
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|     PREAMBLE                                 |                                 |
|---------------------------------------------|      2nd field              |
|   A | B |               C |                D      |                                 |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
for instance.

NB: I might send some mptcp headers as a PR.

**Comment by luismartingarcia** [comment]
Hi Matthieu,

Sorry for the late response. I don't quite understand what you are suggesting here. Is this a bug in the code?

In any case, happy to review PRs to include extra headers (e.g. the MPTCP you mentioned). Please let me know. Thanks!

Luis

**Comment by teto** [comment]
a posterioi, my request doesn't make too much sense. Closing then. Good to know for mptcp, will do !
